name = "ClosestPointSTL"
uuid = "d67795cd-1ce3-49ca-af90-d17877315498"
authors = ["Oriol Colomese <oriol.colomes@gmail.com>"]
version = "1.0.0-DEV"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
